"""
FastAPI layer — section 6.10.

Run with:  uvicorn api.main:app --reload --port 8000
Docs at:   http://localhost:8000/docs   (auto-generated by FastAPI)
"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from ingestion.basil_loader import load_event, list_event_ids
from preprocessing.clean import to_sentences  # noqa: F401  (used indirectly via pipeline)
from analysis.pipeline import analyze_event
from analysis.clustering import cluster_event_sentences
from storage.db import get_conn, init_schema

app = FastAPI(title="NewsLens API")

# Loose during development; tighten to the actual frontend origin before deploying.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
def on_startup():
    init_schema()


class RegisterEventRequest(BaseModel):
    basil_event_id: str


@app.post("/events")
def register_event(req: RegisterEventRequest):
    """Load a BASIL event's articles into the DB and run the full analysis pipeline on it."""
    try:
        articles = load_event(req.basil_event_id)
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))

    with get_conn() as conn:
        row = conn.execute(
            """INSERT INTO events (topic, source_event_id)
               VALUES (%s, %s)
               ON CONFLICT (source_event_id) DO UPDATE SET topic = EXCLUDED.topic
               RETURNING id""",
            (req.basil_event_id, req.basil_event_id),
        ).fetchone()
        event_id = row["id"]

        conn.execute("DELETE FROM articles WHERE event_id = %s", (event_id,))
        conn.execute("DELETE FROM bias_scores WHERE event_id = %s", (event_id,))

        for art in articles:
            conn.execute(
                """INSERT INTO articles (event_id, source, url, raw_text, clean_text)
                   VALUES (%s, %s, %s, %s, %s)""",
                (event_id, art.source, art.url, art.raw_text, art.raw_text),
            )

    analyze_event(event_id)
    return {"event_id": event_id, "sources": [a.source for a in articles]}


@app.get("/basil-events")
def available_basil_events():
    """List BASIL event ids available on disk, for the EventSearch dropdown."""
    return {"event_ids": list_event_ids()}


@app.get("/events")
def list_loaded_events():
    """Events already loaded + analyzed in this DB — lets the frontend skip re-POSTing on reload."""
    with get_conn() as conn:
        rows = conn.execute(
            "SELECT id, topic, source_event_id, created_at FROM events ORDER BY created_at DESC"
        ).fetchall()
    return rows


@app.get("/events/{event_id}/articles")
def get_articles(event_id: int):
    with get_conn() as conn:
        rows = conn.execute(
            """SELECT a.id, a.source, a.url, a.raw_text, e.topic AS event_topic
               FROM articles a JOIN events e ON e.id = a.event_id
               WHERE a.event_id = %s""", (event_id,)
        ).fetchall()
    if not rows:
        raise HTTPException(status_code=404, detail="No articles for that event id")
    return rows


@app.get("/events/{event_id}/entities")
def get_entities(event_id: int):
    with get_conn() as conn:
        rows = conn.execute(
            """SELECT a.source, m.canonical_entity, m.entity_type,
                      SUM(m.mention_count) AS mention_count
               FROM entity_mentions m
               JOIN articles a ON a.id = m.article_id
               WHERE a.event_id = %s
               GROUP BY a.source, m.canonical_entity, m.entity_type
               ORDER BY m.entity_type, mention_count DESC""",
            (event_id,),
        ).fetchall()
    return rows


@app.get("/events/{event_id}/sentiment")
def get_sentiment(event_id: int):
    with get_conn() as conn:
        rows = conn.execute(
            """SELECT a.source, m.canonical_entity, m.entity_type, m.sentiment_score
               FROM entity_mentions m
               JOIN articles a ON a.id = m.article_id
               WHERE a.event_id = %s AND m.sentiment_score IS NOT NULL""",
            (event_id,),
        ).fetchall()
    return rows


@app.get("/events/{event_id}/framing")
def get_framing(event_id: int):
    with get_conn() as conn:
        rows = conn.execute(
            """SELECT source_a, source_b, framing_score, aligned_pairs
               FROM bias_scores WHERE event_id = %s""",
            (event_id,),
        ).fetchall()
    return rows


@app.get("/events/{event_id}/omission")
def get_omission(event_id: int):
    with get_conn() as conn:
        rows = conn.execute(
            """SELECT source_a, source_b, omission_score_a, omission_score_b,
                      topic_overlap_score_a, topic_overlap_score_b,
                      missing_entities_a, missing_entities_b
               FROM bias_scores WHERE event_id = %s""",
            (event_id,),
        ).fetchall()
    return rows


@app.get("/events/{event_id}/bias")
def get_bias_predictions(event_id: int):
    """
    Fine-tuned bias classifier predictions, per source, highest-confidence
    "biased" sentences first. Returns an empty list (not an error) if
    BIAS_MODEL_DIR wasn't configured when the event was analyzed — the
    frontend should treat that as "not available for this event," not a
    failure.
    """
    with get_conn() as conn:
        rows = conn.execute(
            """SELECT a.source, p.sentence, p.biased, p.probability
               FROM sentence_bias_predictions p
               JOIN articles a ON a.id = p.article_id
               WHERE a.event_id = %s AND p.biased = TRUE
               ORDER BY p.probability DESC""",
            (event_id,),
        ).fetchall()
    return rows


@app.get("/events/{event_id}/clusters")
def get_narrative_clusters(event_id: int):
    """
    Runs KMeans narrative clustering on all sentences for this event
    and returns grouped thematic clusters.
    """
    try:
        return cluster_event_sentences(event_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

